In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
customer_id = [
    "CUST" + str(i).zfill(5)
    for i in range(1, 50001)
]
age = np.random.normal(
    loc=25,
    scale=8,
    size=50000
)
age = np.clip(age, 18, 80)
age = np.round(age).astype(int)
gender = np.random.choice(
    ["Male", "Female", "Other"],
    size=50000,
    p=[0.48, 0.47, 0.05]
)
countries = [
    "India",
    "USA",
    "UK",
    "Germany",
    "Canada",
    "Australia",
    "Singapore",
    "UAE"
]
country = np.random.choice(
    countries,
    size=50000,
    p=[0.35, 0.20, 0.10, 0.08, 0.08, 0.07, 0.06, 0.06]
)
employment_types = [
    "Student",
    "Employed",
    "Self-Employed",
    "Business Owner",
    "Retired",
    "Unemployed"
]
employment_type = np.random.choice(
    employment_types,
    size=50000,
    p=[0.12, 0.48, 0.15, 0.10, 0.08, 0.07]
)
income = np.zeros(50000)

income[employment_type == "Student"] = np.random.lognormal(
    mean=np.log(150000),
    sigma=0.7,
    size=(employment_type == "Student").sum()
)

income[employment_type == "Employed"] = np.random.lognormal(
    mean=np.log(800000),
    sigma=0.6,
    size=(employment_type == "Employed").sum()
)
income[employment_type == "Self-Employed"] = np.random.lognormal(
    mean=np.log(1200000),
    sigma=0.7,
    size=(employment_type == "Self-Employed").sum()
)
income[employment_type == "Business Owner"] = np.random.lognormal(
    mean=np.log(2500000),
    sigma=0.9,
    size=(employment_type == "Business Owner").sum()
)
income[employment_type == "Retired"] = np.random.lognormal(
    mean=np.log(600000),
    sigma=0.6,
    size=(employment_type == "Retired").sum()
)
income[employment_type == "Unemployed"] = np.random.lognormal(
    mean=np.log(150000),
    sigma=0.8,
    size=(employment_type == "Unemployed").sum()
)
income = np.clip(income, 0, 10000000)
income = np.round(income, 2)
account_types = [
    "Savings",
    "Current",
    "Salary",
    "Premium"
]
account_type = np.random.choice(
    account_types,
    size=50000,
    p=[0.55, 0.15, 0.20, 0.10]
)
start_time = pd.Timestamp("2023-01-01")
end_day = pd.Timestamp.today()
signup_days = np.random.randint(
    0,
    (end_day - start_time).days + 1,
    size=50000
)
signup_date = start_time + pd.to_timedelta(
    signup_days,
    unit="D"
)
customer_statuses = [
    "Active",
    "Inactive",
    "Suspended",
    "Closed"
]
customer_status = np.random.choice(
    customer_statuses,
    size=50000,
    p=[0.70, 0.15, 0.05, 0.10]
)

In [3]:
customers = pd.DataFrame({
    "customer_id": customer_id,
    "age": age,
    "gender": gender,
    "country": country,
    "employment_type": employment_type,
    "income": income,
    "account_type": account_type,
    "signup_date": signup_date,
    "customer_status": customer_status
})

In [4]:
customers.shape

(50000, 9)

In [5]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      50000 non-null  str
 1   age              50000 non-null  int64
 2   gender           50000 non-null  str
 3   country          50000 non-null  str
 4   employment_type  50000 non-null  str
 5   income           50000 non-null  float64
 6   account_type     50000 non-null  str
 7   signup_date      50000 non-null  datetime64[us]
 8   customer_status  50000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(6)
memory usage: 5.4 MB

In [6]:
customers.head()

,customer_id,age,gender,country,employment_type,income,account_type,signup_date,customer_status
0,CUST00001,18,Male,India,Self-Employed,418705.13,Savings,2024-04-27,Active
1,CUST00002,35,Male,UK,Business Owner,3856117.57,Savings,2024-05-01,Active
2,CUST00003,18,Male,Singapore,Unemployed,259195.80,Premium,2026-04-28,Suspended
3,CUST00004,26,Female,India,Employed,429032.93,Salary,2025-04-07,Active
4,CUST00005,18,Male,India,Business Owner,395098.89,Salary,2026-07-04,Inactive

In [7]:
customers.describe()

                age        income                 signup_date
count  50000.000000  5.000000e+04                       50000
mean      25.802100  1.122270e+06  2024-10-25 13:48:50.111999
min       18.000000  8.079440e+03         2023-01-01 00:00:00
25%       20.000000  3.818499e+05         2023-12-01 00:00:00
50%       25.000000  7.455657e+05         2024-10-25 00:00:00
75%       30.000000  1.314258e+06         2025-09-22 00:00:00
max       57.000000  1.000000e+07         2026-08-17 00:00:00
std        6.739131  1.364260e+06                         NaN

In [8]:
customers.groupby("employment_type")["income"].agg(
    ["count", "mean", "median", "min", "max"]
).round(2)

                 count        mean      median       min          max
employment_type
Business Owner    4960  3392081.87  2514788.83  54402.47  10000000.00
Employed         24058   960367.94   802737.44  55532.78   7613939.50
Retired           4001   732460.46   621936.62  71817.43   5609032.75
Self-Employed     7523  1514140.92  1184975.38  79373.98  10000000.00
Student           6014   192215.65   150960.34  12205.83   2575758.45
Unemployed        3444   205221.83   148359.19   8079.44   3290882.42

In [9]:
income = np.zeros(50000)

# Student
idx = employment_type == "Student"
income[idx] = np.random.lognormal(
    mean=np.log(150000),
    sigma=0.5,
    size=idx.sum()
)
income[idx] = np.clip(income[idx], 0, 500000)

# Employed
idx = employment_type == "Employed"
income[idx] = np.random.lognormal(
    mean=np.log(800000),
    sigma=0.5,
    size=idx.sum()
)
income[idx] = np.clip(income[idx], 200000, 2500000)

# Self-Employed
idx = employment_type == "Self-Employed"
income[idx] = np.random.lognormal(
    mean=np.log(1200000),
    sigma=0.6,
    size=idx.sum()
)
income[idx] = np.clip(income[idx], 300000, 4000000)

# Business Owner
idx = employment_type == "Business Owner"
income[idx] = np.random.lognormal(
    mean=np.log(2500000),
    sigma=0.7,
    size=idx.sum()
)
income[idx] = np.clip(income[idx], 500000, 10000000)

# Retired
idx = employment_type == "Retired"
income[idx] = np.random.lognormal(
    mean=np.log(600000),
    sigma=0.5,
    size=idx.sum()
)
income[idx] = np.clip(income[idx], 100000, 1500000)

# Unemployed
idx = employment_type == "Unemployed"
income[idx] = np.random.lognormal(
    mean=np.log(150000),
    sigma=0.5,
    size=idx.sum()
)
income[idx] = np.clip(income[idx], 0, 300000)

income = np.round(income, 2)

In [10]:
customers["income"] = income

In [11]:
customers.groupby("employment_type")["income"].agg(
    ["count", "mean", "median", "min", "max"]
).round(2)

                 count        mean      median        min         max
employment_type
Business Owner    4960  3123493.07  2496781.28  500000.00  10000000.0
Employed         24058   896702.49   796476.40  200000.00   2500000.0
Retired           4001   671513.39   605528.16  118377.65   1500000.0
Self-Employed     7523  1405464.15  1196053.07  300000.00   4000000.0
Student           6014   167385.49   148198.35   25031.22    500000.0
Unemployed        3444   162469.60   148825.13   20271.86    300000.0

In [12]:
customers["account_type"].value_counts()

account_type
Savings    27619
Salary      9896
Current     7446
Premium     5039
Name: count, dtype: int64

In [13]:
customers["signup_date"].min()

Timestamp('2023-01-01 00:00:00')

In [14]:
customers["signup_date"].max()

Timestamp('2026-08-17 00:00:00')

In [15]:
customers["signup_date"].isna().sum()

np.int64(0)

In [16]:
customers.duplicated().sum()

np.int64(0)

In [17]:
customers_raw = customers.copy()

In [18]:
missing_age_idx = np.random.choice(customers_raw.index,size = 5000,replace = False)
customers_raw.loc[missing_age_idx,"age"] = np.nan

In [19]:
customers_raw["age"].isna().sum()

np.int64(5000)

In [20]:
customers["age"] = age

In [21]:
missing_income_idx = np.random.choice(customers_raw.index,size = 5000,replace = False)
customers_raw.loc[missing_income_idx,"income"] = np.nan

In [22]:
missing_employment_idx = np.random.choice(
    customers_raw.index,
    size=2500,
    replace=False
)

customers_raw.loc[
    missing_employment_idx,
    "employment_type"
] = np.nan

In [23]:
customers_raw.isnull().sum()

customer_id           0
age                5000
gender                0
country               0
employment_type    2500
income             5000
account_type          0
signup_date           0
customer_status       0
dtype: int64

In [24]:
missing_account_idx = np.random.choice(
    customers_raw.index,
    size=2000,
    replace=False
)

customers_raw.loc[
    missing_account_idx,
    "account_type"
] = np.nan

In [25]:
invalid_age_idx = np.random.choice(customers_raw.index[customers_raw["age"].notna()],size = 3000,replace = False)
negative_idx = invalid_age_idx[:1000]
zero_idx = invalid_age_idx[1000:2000]
high_idx = invalid_age_idx[2000:]
customers_raw.loc[negative_idx,"age"] = np.random.randint(-10,0,size = 1000)
customers_raw.loc[negative_idx,"age"] = 0
customers_raw.loc[high_idx,"age"] = np.random.randint(81,121,size = 1000)

In [26]:
customers_raw["age"].describe()

count    45000.000000
mean        26.881178
std         13.539418
min          0.000000
25%         19.000000
50%         25.000000
75%         31.000000
max        120.000000
Name: age, dtype: float64

In [27]:
eligible_income_idx = customers_raw[customers_raw["income"].notna()].index
invalid_income_idx = np.random.choice(eligible_income_idx,size = 2000,replace = False)
customers_raw.loc[invalid_income_idx,"income"] = np.random.randint(-100000,0,size = 2000)

In [28]:
(customers_raw["income"] < 0).sum()

np.int64(2000)

In [29]:
inconsistent_gender_values = [
    "male",
    "M",
    "m",
    "female",
    "F",
    "f",
    "other",
    "O",
    "OTH"
]
eligible_gender_idx = customers_raw[customers_raw["gender"].notna()].index
invalid_gender_idx = np.random.choice(eligible_gender_idx,size = 3000,replace = False)
invalid_gender_values = np.random.choice(inconsistent_gender_values,size = 3000)
customers_raw.loc[invalid_gender_idx,"gender"] = invalid_gender_values

In [30]:
customers_raw["gender"].value_counts()

gender
Male      22411
Female    22241
Other      2348
f           375
female      349
male        339
OTH         339
other       325
M           323
m           321
O           320
F           309
Name: count, dtype: int64

In [31]:
inconsistent_country_values = [
    "india",
    "INDIA",
    "Ind",
    "usa",
    "U.S.",
    "United States",
    "uk",
    "U.K.",
    "United Kingdom",
    "germany",
    "GERMANY",
    "Ger",
    "canada",
    "CAN",
    "australia",
    "Aus",
    "singapore",
    "SG",
    "uae",
    "u.a.e",
    "Emirates"
]
eligible_country_idx = customers_raw[customers_raw["country"].notna()].index
invalid_country_idx = np.random.choice(eligible_country_idx,size = 3000,replace = False)
invalid_country_values = np.random.choice(inconsistent_country_values,size = 3000)
customers.loc[invalid_country_idx,"country"] = invalid_country_values

In [32]:
inconsistent_employment_values = [
    "student",
    "STUDENT",
    "employed",
    "EMPLOYED",
    "self employed",
    "Self employed",
    "SELF-EMPLOYED",
    "business owner",
    "BusinessOwner",
    "BUSINESS OWNER",
    "retired",
    "RETIRED",
    "unemployed",
    "UNEMPLOYED"
]
eligible_employement_idx = customers_raw[customers_raw["employment_type"].notna()].index
invalid_employement_idx = np.random.choice(eligible_employement_idx,size = 3000,replace = False)
invalid_employemeny_values = np.random.choice(inconsistent_employment_values,size = 3000)
customers.loc[invalid_employement_idx,"employment_type"] = invalid_employemeny_values

In [33]:
inconsistent_account_values = [
    "savings",
    "SAVINGS",
    "saving",
    "current",
    "CURRENT",
    "salary",
    "SALARY",
    "salary account",
    "premium",
    "PREMIUM",
    "premium account"
]
eligible_account_idx = customers_raw[customers_raw["account_type"].notna()].index
invalid_account_idx = np.random.choice(eligible_account_idx,size = 2500,replace = False)
invalid_account_values = np.random.choice(inconsistent_account_values,size = 2500)
customers_raw.loc[invalid_account_idx,"account_type"] = invalid_account_values

In [34]:
eligible_date_idx = customers_raw[customers_raw["signup_date"].notna()].index
invalid_date_idx = np.random.choice(eligible_date_idx,size = 3000,replace = False)
today = pd.Timestamp.today().normalize()
future_offsets = np.random.randint(1,366,size = 3000)
future_dates = (today + pd.to_timedelta(future_offsets,unit="D"))
customers.loc[invalid_date_idx,"signup_date"] = future_dates

In [35]:
inconsistent_status_values = [
    "active",
    "ACTIVE",
    "inactive",
    "INACTIVE",
    "suspended",
    "SUSPENDED",
    "closed",
    "CLOSED"
]
eligible_status_idx = customers_raw[
    customers_raw["customer_status"].notna()
].index
invalid_status_idx = np.random.choice(
    eligible_status_idx,
    size=2500,
    replace=False
)
invalid_status_values = np.random.choice(
    inconsistent_status_values,
    size=2500
)
customers_raw.loc[
    invalid_status_idx,
    "customer_status"
] = invalid_status_values

In [36]:
duplicate_rows = customers_raw.sample(
    n=3000,
    replace=False
)
customers_raw = pd.concat(
    [customers_raw, duplicate_rows],
    ignore_index=True
)

In [37]:
customers_raw.to_csv("E:/General_DS_project/Data/Raw/customers.csv",index = False)

In [38]:
transaction_id = [
    "TXN" + str(i).zfill(6)
    for i in range(1, 150001)
]
transaction_customer_id = np.random.choice(
    customers["customer_id"].to_numpy(),
    size=150000,
    replace=True
)
customer_signup_date = customers.set_index(
    "customer_id"
)["signup_date"]
transaction_signup_date = pd.Series(
    transaction_customer_id
).map(customer_signup_date)
transaction_days = np.random.randint(
    0,
    1095,
    size=150000
)
payment_date = (
    transaction_signup_date.reset_index(drop=True)
    + pd.to_timedelta(transaction_days, unit="D")
)

In [39]:
payment_date.isna().sum()

np.int64(0)

In [40]:
amount = np.random.lognormal(mean = np.log(1500),sigma = 1.0,size = 150000)
amount = np.clip(amount,10,100000)
amount = np.round(amount,2)
payment_mode_list = [
    "UPI",
    "Cash",
    "Digital Wallets",
    "Cards",
    "Bank Transfer",
    "Cheque"]
payment_mode = np.random.choice(payment_mode_list,size = 150000,p = [0.70,0.18,0.06,0.04,0.01,0.01])
transaction_status_list = [
    "Success",
    "Failed",
    "Pending",
    "Refunded"]
transaction_status = np.random.choice(
    transaction_status_list,
    size = 150000,
    p = [0.75,0.10,0.05,0.1])
transaction_type_list = [
    "Purchase",
    "Bill Payment",
    "Transfer",
    "Withdrawl",
    "Deposit",
    "Refund",
    "Subscription"]
transaction_type = np.random.choice(
    transaction_type_list,
    size = 150000,
    p = [0.35,0.20,0.15,0.12,0.10,0.05,0.03])

In [41]:
print(len(transaction_id))
print(len(transaction_customer_id))
print(len(payment_date))
print(len(amount))
print(len(payment_mode))
print(len(transaction_status))
print(len(transaction_type))

150000
150000
150000
150000
150000
150000
150000

In [42]:
transactions = pd.DataFrame({
    "transaction_id" : transaction_id,
    "transaction_customer_id" : transaction_customer_id,
    "payment_date" : payment_date,
    "amount" : amount,
    "payment_mode" : payment_mode,
    "transaction_status" : transaction_status,
    "transaction_type" : transaction_type
})

In [43]:
transactions.head()

,transaction_id,transaction_customer_id,payment_date,amount,payment_mode,transaction_status,transaction_type
0,TXN000001,CUST42494,2024-08-03,829.09,UPI,Success,Refund
1,TXN000002,CUST10083,2024-02-16,1185.12,UPI,Success,Transfer
2,TXN000003,CUST17203,2026-05-24,452.11,UPI,Refunded,Withdrawl
3,TXN000004,CUST06717,2025-03-05,9055.75,UPI,Refunded,Withdrawl
4,TXN000005,CUST21272,2029-01-31,3058.19,UPI,Success,Purchase

In [44]:
transactions.shape

(150000, 7)

In [45]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   transaction_id           150000 non-null  str
 1   transaction_customer_id  150000 non-null  str
 2   payment_date             150000 non-null  datetime64[us]
 3   amount                   150000 non-null  float64
 4   payment_mode             150000 non-null  str
 5   transaction_status       150000 non-null  str
 6   transaction_type         150000 non-null  str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 13.4 MB

In [46]:
transactions.describe()

                     payment_date         amount
count                      150000  150000.000000
mean   2026-06-15 02:36:43.776000    2462.806915
min           2023-01-04 00:00:00      19.950000
25%           2025-05-28 00:00:00     762.275000
50%           2026-06-06 00:00:00    1489.500000
75%           2027-06-28 00:00:00    2933.860000
max           2030-07-30 00:00:00   95471.960000
std                           NaN    3173.038984

In [47]:
transactions["transaction_id"].duplicated().sum()

np.int64(0)

In [48]:
transactions_clean = transactions.copy()
transactions_raw = transactions.copy()

In [49]:
missing_payment_mode_idx = np.random.choice(transactions_raw.index,size = 5000,replace = False)
transactions_raw.loc[missing_payment_mode_idx,"payment_mode"] =  np.nan

In [50]:
transactions_raw["payment_mode"].isnull().sum()

np.int64(5000)

In [51]:
missing_amount_idx = np.random.choice(transactions_raw.index,size = 3000,replace = False)
transactions_raw.loc[missing_amount_idx,"amount"] = np.nan

In [52]:
missing_transaction_type_idx = np.random.choice(transactions_raw.index,size = 2500,replace = False)
transactions_raw.loc[missing_transaction_type_idx,"transaction_type"] = np.nan

In [53]:
eligible_amount_idx = np.random.choice(transactions_raw.index[transactions_raw["amount"].notna()],size = 3000,replace = False)
negative_amount_idx = np.random.choice(eligible_amount_idx,size = 1500,replace = False)
zero_amount_idx = np.random.choice(eligible_amount_idx,size = 1500,replace = False)
transactions_raw.loc[negative_amount_idx,"amount"] = np.random.randint(-100000,0,size = 1500)
transactions_raw.loc[negative_amount_idx,"amount"] = 0

In [54]:
eligible_payment_dates_idx = np.random.choice(transactions_raw.index,size = 3000,replace = False)
today_date = pd.Timestamp.today().normalize()
future_payment_dates_offsets = np.random.randint(1,366,size = 3000)
future_payment_dates = today_date + pd.to_timedelta(future_payment_dates_offsets,unit="D")
transactions_raw.loc[eligible_payment_dates_idx,"payment_date"] = future_payment_dates

In [55]:
inconsistent_payment_modes = [
    "upi",
    "UPI Payment",
    "cash",
    "digital wallet",
    "wallet",
    "card",
    "credit card",
    "debit card",
    "bank transfer",
    "BankTransfer",
    "cheque",
    "Cheque Payment"]
eligible_payment_mode_idx = np.random.choice(transactions_raw.index[transactions_raw["payment_mode"].notna()],size = 4000,replace = False)
invalid_payment_values = np.random.choice(inconsistent_payment_modes,size = 4000)
transactions_raw.loc[eligible_payment_mode_idx,"payment_mode"] = invalid_payment_values

In [56]:
inconsistent_transaction_status = [
    "success",
    "SUCCESS",
    "failed",
    "FAIL",
    "pending",
    "PROCESSING",
    "refunded",
    "REFUNDED",
    "cancelled",
    "CANCELLED"
]
invalid_transaction_status_idx = np.random.choice(transactions_raw.index[transactions_raw["transaction_status"].notna()],size = 4000,replace = False)
invalid_transaction_status_values = np.random.choice(inconsistent_transaction_status,size = 4000)
transactions_raw.loc[invalid_transaction_status_idx,"transaction_status"] = invalid_transaction_status_values

In [57]:
inconsistent_transaction_type = [
    "purchase",
    "PURCHASE",
    "Purchase",
    "bill payment",
    "BILL PAYMENT",
    "Bill payment",
    "transfer",
    "TRANSFER",
    "Transfer",
    "withdrawal",
    "WITHDRAWAL",
    "Withdrawl",
    "deposit",
    "DEPOSIT",
    "Deposit",
    "refund",
    "REFUND",
    "Refund",
    "subscription",
    "SUBSCRIPTION",
    "Subscription"
]
invalid_transactin_type_idx = np.random.choice(transactions_raw.index[transactions_raw["transaction_type"].notna()],size = 4000,replace = False)
invalid_transaction_type_values = np.random.choice(inconsistent_transaction_type,size = 4000)
transactions_raw.loc[invalid_transactin_type_idx,"transaction_type"] = invalid_transaction_type_values

In [58]:
duplicate_rows_transaction = transactions_raw.sample(
    n = 5000,
    replace = False)
transactions_raw = pd.concat(
    [transactions_raw,duplicate_rows_transaction],
    ignore_index = True)

In [59]:
transactions_raw.shape

(155000, 7)

In [60]:
transactions_raw.describe()

                     payment_date         amount
count                      155000  151899.000000
mean   2026-06-20 11:32:49.548387    2437.110515
min           2023-01-04 00:00:00       0.000000
25%           2025-06-07 00:00:00     741.435000
50%           2026-06-21 00:00:00    1470.110000
75%           2027-06-24 00:00:00    2911.190000
max           2030-07-30 00:00:00   95471.960000
std                           NaN    3160.687774

In [61]:
transactions_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 155000 entries, 0 to 154999
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   transaction_id           155000 non-null  str
 1   transaction_customer_id  155000 non-null  str
 2   payment_date             155000 non-null  datetime64[us]
 3   amount                   151899 non-null  float64
 4   payment_mode             149815 non-null  str
 5   transaction_status       155000 non-null  str
 6   transaction_type         152411 non-null  str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 13.9 MB

In [62]:
transactions_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 155000 entries, 0 to 154999
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   transaction_id           155000 non-null  str
 1   transaction_customer_id  155000 non-null  str
 2   payment_date             155000 non-null  datetime64[us]
 3   amount                   151899 non-null  float64
 4   payment_mode             149815 non-null  str
 5   transaction_status       155000 non-null  str
 6   transaction_type         152411 non-null  str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 13.9 MB

In [63]:
transactions_raw.shape

(155000, 7)

In [64]:
transactions_raw.rename(
    columns={"transaction_customer_id": "customer_id"},
    inplace=True
)

In [65]:
transactions_raw.duplicated().sum()

np.int64(5000)

In [66]:
transactions_raw["transaction_id"].duplicated().sum()

np.int64(5000)

In [67]:
duplicate_idx = transactions_raw[
    transactions_raw["transaction_id"].duplicated(keep="first")
].index

remove_idx = duplicate_idx[:5000]

transactions_raw = transactions_raw.drop(remove_idx)

In [68]:
transactions_raw.shape

(150000, 7)

In [69]:
transactions_raw.to_csv("E:/General_DS_project/Data/Raw/transactions.csv",index = False)

In [70]:
activity_id = ["ACT" + str(i).zfill(6) for i in range(1,300001)]

In [71]:
activity_customer_id = np.random.choice(
    customers["customer_id"].to_numpy(),
    size = 300000,
    replace = True)
customer_signup_date = customers.set_index("customer_id")["signup_date"]
activity_customer_signup = pd.Series(activity_customer_id).map(customer_signup_date)
activity_dates = np.random.randint(0,1096,size = 300000)
activity_timestamp = activity_customer_signup.reset_index(drop = True) + pd.to_timedelta(activity_dates,unit="D")
activity_types = [
    "Login",
    "Logout",
    "View Account",
    "Transfer",
    "Payment",
    "Deposit",
    "Withdrawal",
    "Profile Update"
]
activity_type = np.random.choice(activity_types,size = 300000,p = [0.25, 0.10, 0.35, 0.10, 0.10, 0.04, 0.04, 0.02])

In [72]:
device_types = ["Mobile", "Desktop", "Tablet"]
device_type = np.random.choice(device_types,size = 300000,p = [0.65, 0.25, 0.10])
os_types = ["Android", "iOS", "Windows", "Web"]
os_type = np.random.choice(os_types,size = 300000,p = [0.40, 0.30, 0.10, 0.20])
session_duration = np.random.lognormal(mean = np.log(15),sigma = 0.8,size = 300000)
session_duration = np.clip(session_duration,1,180)
session_duration = np.round(session_duration,2)

In [73]:
activity_logs = pd.DataFrame({
    "activity_id": activity_id,
    "customer_id": activity_customer_id,
    "activity_timestamp": activity_timestamp,
    "activity_type": activity_type,
    "device_type": device_type,
    "platform": os_type,
    "session_duration": session_duration
})

In [74]:
print("activity_id:", len(activity_id))
print("customer_id:", len(activity_customer_id))
print("activity_timestamp:", len(activity_timestamp))
print("activity_type:", len(activity_type))
print("device_type:", len(device_type))
print("platform:", len(os_type))
print("session_duration:", len(session_duration))

activity_id: 300000
customer_id: 300000
activity_timestamp: 300000
activity_type: 300000
device_type: 300000
platform: 300000
session_duration: 300000

In [75]:
activity_logs_clean = activity_logs.copy()
activity_logs_raw = activity_logs.copy()

In [76]:
missing_device_type_idx = np.random.choice(activity_logs.index,size = 10000,replace = False)
activity_logs.loc[missing_device_type_idx,"device_type"] = np.nan

In [77]:
missing_activity_type_idx = np.random.choice(activity_logs.index,size = 7000,replace = False)
activity_logs.loc[missing_activity_type_idx,"activity_type"] = np.nan
missing_session_duration_idx = np.random.choice(activity_logs.index,size = 5000,replace = False)
activity_logs.loc[missing_session_duration_idx,"session_duration"] = np.nan

In [78]:
eligible_session_duration_idx = activity_logs.index[activity_logs["session_duration"].notna()]
invalid_session_duration_idx = np.random.choice(eligible_session_duration_idx,size = 3000,replace = False)
zero_session_duration_idx = np.random.choice(invalid_session_duration_idx,size = 1500, replace = False)
negative_session_duration_idx = np.random.choice(invalid_session_duration_idx,size = 1500,replace = False)
activity_logs.loc[zero_session_duration_idx,"session_duration"] = 0
activity_logs.loc[zero_session_duration_idx,"session_duration"] = np.random.randint(-180,0,size = 1500)

In [79]:
today = pd.Timestamp.today().normalize()
future_offsets = np.random.randint(0,366,size = 3000)
eligible_activity_timestamps = np.random.choice(activity_logs.index,size = 3000,replace = False)
future_dates_offset_activity = today + pd.to_timedelta(future_offsets,unit="D")

In [82]:
inconsistent_activity_types = [
    "Login",
    "login",
    "LOGOUT",
    "Logout ",
    "ViewAccount",
    "View Account",
    "Transfer",
    "transfer",
    "Payment",
    "PAYMENT",
    "Deposit",
    "deposit",
    "Withdrawal",
    "Withdraw",
    "Profile Update",
    "ProfileUpdate",
    "Profile update",
]
eligible_activity_index = activity_logs_raw.index[activity_logs_raw["activity_type"].notna()]
invalid_activity_index = np.random.choice(eligible_activity_index,size = 4000,replace = False)
invalid_activity_types = np.random.choice(inconsistent_activity_types,size = 4000)
activity_logs_raw.loc[invalid_activity_index,"activity_type"] = invalid_activity_types

In [84]:
inconsistent_device_types = [
    "mobile",
    "MOBILE",
    "Mobile ",
    "PC",
    "pc",
    "desktop",
    "DESKTOP",
    "Desktop ",
    "tab",
    "TAB",
    "tablet",
    "TABLET",
    "Tablet ",
]
eligible_dveice_type_index = activity_logs_raw.index[activity_logs_raw["device_type"].notna()]
invalid_device_type_index = np.random.choice(eligible_dveice_type_index,size = 3000,replace = False)
invalid_device_type = np.random.choice(inconsistent_device_types,size = 3000)
activity_logs_raw.loc[invalid_device_type_index,"device_type"] = invalid_device_type

In [85]:
inconsistent_os_type = [
    "Android",
    "android",
    "ANDROID",
    "iOS",
    "IOS",
    "ios",
    "Windows",
    "windows",
    "WINDOWS",
    "Web",
    "web",
    "WEB",
]
eligible_os_type_idx = activity_logs_raw.index[activity_logs_raw["platform"].notna()]
invalid_os_type_idx = np.random.choice(eligible_os_type_idx,size = 3000,replace = False)
invalid_os_types = np.random.choice(inconsistent_os_type,replace = 3000)
activity_logs_raw.loc[eligible_os_type_idx,"platform"] = invalid_os_types

In [86]:
activity_duplicates = activity_logs_raw.sample(n = 5000,replace = False)
activity_logs_raw = pd.concat([activity_logs_raw,activity_duplicates],ignore_index = True)

In [87]:
activity_logs_raw.shape

(305000, 7)

In [88]:
activity_logs_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 305000 entries, 0 to 304999
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   activity_id         305000 non-null  str
 1   customer_id         305000 non-null  str
 2   activity_timestamp  305000 non-null  datetime64[us]
 3   activity_type       305000 non-null  str
 4   device_type         305000 non-null  str
 5   platform            305000 non-null  str
 6   session_duration    305000 non-null  float64
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 27.9 MB

In [90]:
activity_logs_raw.to_csv("E:/General_DS_project/Data/Raw/activity_logs.csv",index = False)